[build]
  command = "npm run build"
  publish = "_site"

[functions]
  directory = "netlify/functions"
  included_files = ["src/_data/cities.json"]

[[redirects]]
  from = "/contact"
  to = "/local-presentations/"
  status = 301

[[redirects]]
  from = "/contact/"
  to = "/local-presentations/"
  status = 301

[[redirects]]
  from = "/local-presentation"
  to = "/local-presentations/"
  status = 301

[[redirects]]
  from = "/local-presentation/"
  to = "/local-presentations/"
  status = 301

[[redirects]]
  from = "/christadelphians"
  to = "/about/"
  status = 301

[[redirects]]
  from = "/christadelphians/"
  to = "/about/"
  status = 301
